version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/alm-app/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "frontend"]

  - package-ecosystem: "pip"
    directory: "/alm-app/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "backend"]
